ARG ELK_VERSION

# https://www.docker.elastic.co/
FROM docker.elastic.co/elasticsearch/elasticsearch:${ELK_VERSION}

# Add elasticsearch plugins setup here
# ie: RUN elasticsearch-plugin install analysis-icu